# Generated by Django 4.0.2 on 2022-05-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='be_dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('organisation', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('firm', models.CharField(max_length=500)),
                ('gst', models.CharField(max_length=500)),
                ('account', models.IntegerField(max_length=500)),
                ('ifsc', models.CharField(max_length=500)),
                ('accountholder', models.CharField(max_length=500)),
            ],
        ),
    ]
