# Generated by Django 4.0.2 on 2022-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.IntegerField()),
                ('service', models.CharField(max_length=500)),
                ('enquiry', models.TextField(max_length=1000)),
            ],
        ),
    ]
