# Generated by Django 4.0.2 on 2022-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=500)),
                ('s1', models.CharField(max_length=500)),
                ('s2', models.CharField(max_length=500)),
                ('speed', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
