# Generated by Django 4.0.2 on 2022-05-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_product_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
